[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

; 1. The Automated Librarian: This downloads the libraries for you
lib_deps =
    # Use the direct GitHub link to bypass registry errors
    https://github.com/ricardoquesada/bluepad32.git
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1

; 2. The Speedometer: Set this to match your code's Serial.begin(115200)
monitor_speed = 115200

; 3. Bluetooth Flags: Helps the compiler handle the PS4 Bluetooth stack
build_flags = 
    -D CORE_DEBUG_LEVEL=2